/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Datas;
import control.TextSize;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.Despesa;
import model.Endereco;

/**
 *
 * @author Luiz
 */
public class FrmCadastroDespesa extends javax.swing.JFrame {

    public FrmCadastroDespesa(int nvlAdm) {
        initComponents();
        inicializarTabela();
        MaskFormatter dateMask;
        try {
            dateMask = new MaskFormatter("##/##/####");
            dateMask.setPlaceholderCharacter('*');
            dateMask.install(txtfDataVencimento);
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastroDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtfDataVencimento.setText(Datas.getDiaHoje());

        selecionarAoFocar();

        if (nvlAdm == 0) {
            btnCadastrar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescricaoDespesa = new javax.swing.JTextArea();
        lblDescrição = new javax.swing.JLabel();
        cmbTipoDespesa = new javax.swing.JComboBox<>();
        btnListarDespesas = new javax.swing.JButton();
        lblTipoDespesa = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        lblValorDespesa = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblVencimento = new javax.swing.JLabel();
        txtfDataVencimento = new javax.swing.JFormattedTextField();
        txtfValorDespesa = new javax.swing.JFormattedTextField();
        btnMenuPrincipal = new javax.swing.JButton();
        btnFecharFrame = new javax.swing.JButton();
        lblDespesaRecente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDespesaRecente = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Despesa");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logopng32.png")));
        setMinimumSize(new java.awt.Dimension(1152, 648));
        setResizable(false);
        getContentPane().setLayout(null);

        panPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panPrincipal.setOpaque(false);
        panPrincipal.setLayout(null);

        txaDescricaoDespesa.setColumns(20);
        txaDescricaoDespesa.setLineWrap(true);
        txaDescricaoDespesa.setRows(5);
        txaDescricaoDespesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txaDescricaoDespesaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txaDescricaoDespesa);

        panPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(10, 83, 1100, 180);

        lblDescrição.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDescrição.setText("Descrição detalhada da Despesa:");
        panPrincipal.add(lblDescrição);
        lblDescrição.setBounds(10, 50, 343, 25);

        cmbTipoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serviço", "Obrigações", "Salarios a pagar" }));
        panPrincipal.add(cmbTipoDespesa);
        cmbTipoDespesa.setBounds(166, 10, 215, 25);

        btnListarDespesas.setText("Listar Despesas Cadastradas");
        btnListarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDespesasActionPerformed(evt);
            }
        });
        panPrincipal.add(btnListarDespesas);
        btnListarDespesas.setBounds(570, 270, 210, 30);

        lblTipoDespesa.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblTipoDespesa.setText("Tipo de despesa:");
        panPrincipal.add(lblTipoDespesa);
        lblTipoDespesa.setBounds(10, 10, 150, 25);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        panPrincipal.add(btnLimpar);
        btnLimpar.setBounds(820, 270, 100, 30);

        lblValorDespesa.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblValorDespesa.setText("Valor da despesa:");
        panPrincipal.add(lblValorDespesa);
        lblValorDespesa.setBounds(770, 10, 150, 25);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCadastrar);
        btnCadastrar.setBounds(950, 270, 130, 30);

        lblVencimento.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblVencimento.setText("Data de Vencimento:");
        panPrincipal.add(lblVencimento);
        lblVencimento.setBounds(409, 10, 171, 25);

        txtfDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        panPrincipal.add(txtfDataVencimento);
        txtfDataVencimento.setBounds(590, 10, 128, 25);

        txtfValorDespesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtfValorDespesa.setText("0,00");
        txtfValorDespesa.setNextFocusableComponent(txaDescricaoDespesa);
        txtfValorDespesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfValorDespesaKeyReleased(evt);
            }
        });
        panPrincipal.add(txtfValorDespesa);
        txtfValorDespesa.setBounds(930, 10, 125, 25);

        getContentPane().add(panPrincipal);
        panPrincipal.setBounds(10, 10, 1125, 310);

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal);
        btnMenuPrincipal.setBounds(900, 550, 130, 30);

        btnFecharFrame.setText("Fechar ");
        btnFecharFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFrameActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecharFrame);
        btnFecharFrame.setBounds(1055, 550, 80, 30);

        lblDespesaRecente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDespesaRecente.setText("Despesas Cadastradas Recentemente:");
        getContentPane().add(lblDespesaRecente);
        lblDespesaRecente.setBounds(10, 320, 350, 25);

        tblDespesaRecente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDespesaRecente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 350, 1125, 190);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, -20, 1150, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarDespesa();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnListarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDespesasActionPerformed
        control.Janelas.abrirListagemDespesa();
    }//GEN-LAST:event_btnListarDespesasActionPerformed

    private void txaDescricaoDespesaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaDescricaoDespesaKeyReleased
        txaDescricaoDespesa.setText(TextSize.maxLenghtDescricaoDespesa(txaDescricaoDespesa.getText()));
    }//GEN-LAST:event_txaDescricaoDespesaKeyReleased

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        control.Janelas.focarPrincipal();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void txtfValorDespesaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfValorDespesaKeyReleased
        txtfValorDespesa.setText(control.TextSize.maxLenghtValorDespesa(txtfValorDespesa.getText()));
    }//GEN-LAST:event_txtfValorDespesaKeyReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFrameActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroDespesa(control.SynchroSoft.getNvlAdm()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFecharFrame;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListarDespesas;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JComboBox<String> cmbTipoDespesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDescrição;
    private javax.swing.JLabel lblDespesaRecente;
    private javax.swing.JLabel lblTipoDespesa;
    private javax.swing.JLabel lblValorDespesa;
    private javax.swing.JLabel lblVencimento;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JTable tblDespesaRecente;
    private javax.swing.JTextArea txaDescricaoDespesa;
    private javax.swing.JFormattedTextField txtfDataVencimento;
    private javax.swing.JFormattedTextField txtfValorDespesa;
    // End of variables declaration//GEN-END:variables

    private void cadastrarDespesa() {
        //try {
            Despesa despesa = new Despesa(txtfDataVencimento.getText(), cmbTipoDespesa.getSelectedItem().toString(),
                    txaDescricaoDespesa.getText(), txtfValorDespesa.getText(), false);
            if (validarCampos()) {
                boolean cadastroSucedido = dao.DaoDespesa.cadastrarDespesa(despesa);
                if (cadastroSucedido) {
                    atualizarTabela(despesa);
                }
            }

        /*} catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao popular atributos de despesa. \n\nExceção JAVA:\n"
                    + ex, "Erro ao cadastrar despesas", 0);
        }*/
    }

    private void limpar() {
        cmbTipoDespesa.setSelectedIndex(0);
        txtfValorDespesa.setText("0,00");
        txaDescricaoDespesa.setText("");
    }

    private void selecionarAoFocar() {
        txtfDataVencimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfDataVencimento.selectAll();
                    }
                });
            }
        });

        txtfValorDespesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfValorDespesa.selectAll();
                    }
                });
            }
        });
    }

    private void inicializarTabela() {
        String[] nomeColunas = {"Tipo Despesa", "Vencimento", "Valor", "Descrição", "Quitada"};
        try {
            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tblDespesaRecente.setModel(model);
            model.setColumnIdentifiers(nomeColunas);
            model.setRowCount(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao popular tabela de cadastros recentes.\n\n" + ex.getMessage(), "Erro ao popular tabela", 0);
        }
    }

    private void atualizarTabela(Despesa despesa) {
        Object rowData[] = new Object[5];

        rowData[0] = despesa.getTipoDespesas();
        rowData[1] = despesa.getDataDespesa();
        rowData[2] = despesa.getValorDespesaSTR();
        rowData[3] = despesa.getDescricaoDespesa();
        rowData[4] = despesa.getQuitadaSTR();

        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblDespesaRecente.getModel();
        model.addRow(rowData);
    }

    private boolean validarCampos() {
        if (txtfValorDespesa.getValue().equals("0,00")) {
            JOptionPane.showMessageDialog(null, "Valor da despesa zerado.\n\n"
                    + "Informe o valor da despesa maior que zero.", "Erro - Valor da despesa inválido.", 0);
            return false;
        } else {
            return true;
        }
    }
}
