/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Datas;
import control.TextSize;
import dao.DaoEndereco;
import dao.DaoFuncionario;
import dao.DaoPessoa;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.Endereco;
import model.Funcionario;
import model.Pessoa;
import model.PessoaFisica;

/**
 *
 * @author Luiz
 */
public class FrmCadastroFuncionario extends javax.swing.JFrame {

    boolean codCadastrado;
    boolean cpfCadastrado;
    Endereco endExibicao;
    PessoaFisica pessoaFisicaExibicao;
    Pessoa pessoaExibicao;

    /**
     * Creates new form FrmCadastroPeca
     */
    public FrmCadastroFuncionario(int nvlAdm) {
        initComponents();
        this.endExibicao = new Endereco();
        this.pessoaFisicaExibicao = new PessoaFisica();
        this.pessoaExibicao = new Pessoa();

        MaskFormatter dateMask;
        try {
            dateMask = new MaskFormatter("##/##/####");
            dateMask.setPlaceholderCharacter('*');
            dateMask.install(txtfDataAdmissao);
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastroDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtfDataAdmissao.setText(Datas.getDiaHoje());
        iniciarlizarTabela();
        if (nvlAdm == 0) {
            btnCadastrar.setEnabled(false);
        }

        selecionarAoFocar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoNivelADM = new javax.swing.ButtonGroup();
        grupoSexoExib = new javax.swing.ButtonGroup();
        panPrincipal = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        lblCodigoFuncionario = new javax.swing.JLabel();
        txtCodigoFuncionario = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnListarFuncionarios = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblHorasTrabalhadas = new javax.swing.JLabel();
        lblNivelAdm = new javax.swing.JLabel();
        rbtVisualizacao = new javax.swing.JRadioButton();
        rbtCompleto = new javax.swing.JRadioButton();
        lblCpfExiste = new javax.swing.JLabel();
        btnCadastrarPessoa = new javax.swing.JButton();
        panDadosPessoa = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNomePessoa = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        lblLogradouro = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        Bairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        Bairro1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        lblSexoDesc = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblSexoValor = new javax.swing.JLabel();
        lblCodigoExiste = new javax.swing.JLabel();
        txtfSalario = new javax.swing.JFormattedTextField();
        txtfHoras = new javax.swing.JFormattedTextField();
        lblDataAdmissao = new javax.swing.JLabel();
        txtfDataAdmissao = new javax.swing.JFormattedTextField();
        btnHoje = new javax.swing.JButton();
        btnMenuPrincipal1 = new javax.swing.JButton();
        btnFecharFrame1 = new javax.swing.JButton();
        lblFuncionarioRecente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarioRecente = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logopng32.png")));
        setMinimumSize(new java.awt.Dimension(1152, 648));
        setResizable(false);
        setSize(new java.awt.Dimension(1152, 648));
        getContentPane().setLayout(null);

        panPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        panPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1152, 648));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1152, 648));
        panPrincipal.setOpaque(false);
        panPrincipal.setPreferredSize(new java.awt.Dimension(1152, 648));

        lblCpf.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCpf.setText("CPF");

        txtCpf.setNextFocusableComponent(txtCargo);
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });

        lblSalario.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblSalario.setText("Salário");

        lblCodigoFuncionario.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCodigoFuncionario.setText("Código do Funcionário");

        txtCodigoFuncionario.setNextFocusableComponent(txtCpf);
        txtCodigoFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoFuncionarioKeyReleased(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setNextFocusableComponent(txtCodigoFuncionario);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnListarFuncionarios.setText("Listar Funcionários");
        btnListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFuncionariosActionPerformed(evt);
            }
        });

        lblCargo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCargo.setText("Cargo a ser exercido");

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCargoKeyReleased(evt);
            }
        });

        lblHorasTrabalhadas.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblHorasTrabalhadas.setText("Horas Mensais");

        lblNivelAdm.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblNivelAdm.setText("Nível Administrativo do Sistema:");

        grupoNivelADM.add(rbtVisualizacao);
        rbtVisualizacao.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        rbtVisualizacao.setSelected(true);
        rbtVisualizacao.setText("Visualização");
        rbtVisualizacao.setOpaque(false);
        rbtVisualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVisualizacaoActionPerformed(evt);
            }
        });

        grupoNivelADM.add(rbtCompleto);
        rbtCompleto.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        rbtCompleto.setText("Completo");
        rbtCompleto.setOpaque(false);
        rbtCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCompletoActionPerformed(evt);
            }
        });

        lblCpfExiste.setForeground(java.awt.Color.red);
        lblCpfExiste.setText("CPF Inválido.");

        btnCadastrarPessoa.setText("Cadastrar CPF");
        btnCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPessoaActionPerformed(evt);
            }
        });

        panDadosPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Pessoa"));
        panDadosPessoa.setOpaque(false);

        lblNome.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblNome.setText("Nome");

        txtNomePessoa.setEditable(false);
        txtNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePessoaActionPerformed(evt);
            }
        });

        lblTelefone.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");

        txtTelefone.setEditable(false);

        lblCelular.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCelular.setText("Celular");

        lblLogradouro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblLogradouro.setText("Logradouro");

        txtLogradouro.setEditable(false);

        lblCidade.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCidade.setText("Cidade");

        txtCidade.setEditable(false);

        lblEstado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblEstado.setText("Estado");

        txtEstado.setEditable(false);

        Bairro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        Bairro.setText("Bairro");

        txtBairro.setEditable(false);

        Bairro1.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        Bairro1.setText("N° Logradouro");

        txtNumero.setEditable(false);

        txtCelular.setEditable(false);

        lblSexoDesc.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblSexoDesc.setText("Sexo:");

        lblCep.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCep.setText("CEP");

        txtCep.setEditable(false);

        lblSexoValor.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblSexoValor.setText("-");

        javax.swing.GroupLayout panDadosPessoaLayout = new javax.swing.GroupLayout(panDadosPessoa);
        panDadosPessoa.setLayout(panDadosPessoaLayout);
        panDadosPessoaLayout.setHorizontalGroup(
            panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                .addComponent(Bairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtCidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                        .addComponent(Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDadosPessoaLayout.createSequentialGroup()
                                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDadosPessoaLayout.createSequentialGroup()
                                        .addComponent(lblLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                                        .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSexoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                        .addComponent(lblSexoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panDadosPessoaLayout.setVerticalGroup(
            panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNome))
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogradouro)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexoDesc)
                            .addComponent(lblSexoValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelular)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panDadosPessoaLayout.createSequentialGroup()
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCidade)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEstado)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bairro)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bairro1)
                            .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCodigoExiste.setForeground(java.awt.Color.red);
        lblCodigoExiste.setText("Código inválido.");

        txtfSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtfSalario.setText("0,00");
        txtfSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfSalarioMouseClicked(evt);
            }
        });
        txtfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfSalarioKeyReleased(evt);
            }
        });

        txtfHoras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtfHoras.setText("0");
        txtfHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfHorasKeyReleased(evt);
            }
        });

        lblDataAdmissao.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDataAdmissao.setText("Data Admissão");

        txtfDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtfDataAdmissao.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N

        btnHoje.setText("Hoje");
        btnHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHojeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblNivelAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(rbtVisualizacao)
                            .addGap(10, 10, 10)
                            .addComponent(rbtCompleto)
                            .addGap(271, 271, 271)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panPrincipalLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(panDadosPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCodigoFuncionario)
                                .addGap(10, 10, 10)
                                .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblCodigoExiste, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btnListarFuncionarios)
                                .addGap(48, 48, 48)
                                .addComponent(lblCpf)
                                .addGap(11, 11, 11)
                                .addComponent(txtCpf))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblCargo)
                                .addGap(27, 27, 27)
                                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lblDataAdmissao)
                                .addGap(7, 7, 7)
                                .addComponent(txtfDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHoje)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(lblSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHorasTrabalhadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(lblCpfExiste, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrarPessoa)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblCodigoExiste))
                            .addComponent(btnListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblCpf))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCodigoFuncionario)
                                    .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpfExiste)
                            .addComponent(btnCadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSalario)
                                    .addComponent(txtfHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHorasTrabalhadas)))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDataAdmissao))
                            .addComponent(lblCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblNivelAdm))
                            .addComponent(rbtVisualizacao)
                            .addComponent(rbtCompleto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDadosPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panPrincipal);
        panPrincipal.setBounds(30, 30, 1100, 310);

        btnMenuPrincipal1.setText("Menu Principal");
        btnMenuPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipal1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal1);
        btnMenuPrincipal1.setBounds(900, 550, 130, 30);

        btnFecharFrame1.setText("Fechar ");
        btnFecharFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFrame1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecharFrame1);
        btnFecharFrame1.setBounds(1050, 550, 80, 30);

        lblFuncionarioRecente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblFuncionarioRecente.setText("Funcionários Cadastrados Recentemente:");
        getContentPane().add(lblFuncionarioRecente);
        lblFuncionarioRecente.setBounds(30, 350, 350, 25);

        tblFuncionarioRecente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarioRecente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 380, 1100, 160);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, -20, 1150, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipal1ActionPerformed
        control.Janelas.focarPrincipal();
    }//GEN-LAST:event_btnMenuPrincipal1ActionPerformed

    private void btnFecharFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFrame1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharFrame1ActionPerformed

    private void txtfHorasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfHorasKeyReleased
        txtfHoras.setText(control.TextSize.maxLenghtHoraMensal(txtfHoras.getText()));
    }//GEN-LAST:event_txtfHorasKeyReleased

    private void txtfSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfSalarioKeyReleased
        txtfSalario.setText(control.TextSize.maxLenghtSalario(txtfSalario.getText()));
    }//GEN-LAST:event_txtfSalarioKeyReleased

    private void txtNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePessoaActionPerformed

    private void btnCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPessoaActionPerformed
        control.Janelas.abrirCadastroPessoa();
    }//GEN-LAST:event_btnCadastrarPessoaActionPerformed

    private void rbtCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCompletoActionPerformed

    }//GEN-LAST:event_rbtCompletoActionPerformed

    private void rbtVisualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVisualizacaoActionPerformed

    }//GEN-LAST:event_rbtVisualizacaoActionPerformed

    private void txtCargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyReleased
        txtCargo.setText(TextSize.maxLenghtCargo(txtCargo.getText()));
    }//GEN-LAST:event_txtCargoKeyReleased

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void btnListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFuncionariosActionPerformed
        control.Janelas.abrirListagemFuncionario();
    }//GEN-LAST:event_btnListarFuncionariosActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarFuncionario();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodigoFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioKeyReleased
        txtCodigoFuncionario.setText(TextSize.maxLenghtFuncionario(txtCodigoFuncionario.getText()));
        verificarCodigoFuncionario();
    }//GEN-LAST:event_txtCodigoFuncionarioKeyReleased

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        txtCpf.setText(TextSize.maxLenghtCPFCNPJ(txtCpf.getText(), true));
        verificarCpfExiste();
    }//GEN-LAST:event_txtCpfKeyReleased

    private void btnHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHojeActionPerformed
        txtfDataAdmissao.setText(control.Datas.getDiaHoje());
    }//GEN-LAST:event_btnHojeActionPerformed

    private void txtfSalarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfSalarioMouseClicked
        txtfDataAdmissao.selectAll();
    }//GEN-LAST:event_txtfSalarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroFuncionario(control.SynchroSoft.getNvlAdm()).setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JLabel Bairro1;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarPessoa;
    private javax.swing.JButton btnFecharFrame1;
    private javax.swing.JButton btnHoje;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListarFuncionarios;
    private javax.swing.JButton btnMenuPrincipal1;
    private javax.swing.ButtonGroup grupoNivelADM;
    private javax.swing.ButtonGroup grupoSexoExib;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigoExiste;
    private javax.swing.JLabel lblCodigoFuncionario;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpfExiste;
    private javax.swing.JLabel lblDataAdmissao;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFuncionarioRecente;
    private javax.swing.JLabel lblHorasTrabalhadas;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNivelAdm;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSexoDesc;
    private javax.swing.JLabel lblSexoValor;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel panDadosPessoa;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JRadioButton rbtCompleto;
    private javax.swing.JRadioButton rbtVisualizacao;
    private javax.swing.JTable tblFuncionarioRecente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNomePessoa;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JFormattedTextField txtfDataAdmissao;
    private javax.swing.JFormattedTextField txtfHoras;
    private javax.swing.JFormattedTextField txtfSalario;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        txtCodigoFuncionario.setText("");
        txtCpf.setText("");
        txtCargo.setText("");
        txtfSalario.setText("0,00");
        txtfHoras.setText("0");
        rbtVisualizacao.setSelected(true);
        limparExibicaoPessoa();
        lblCodigoExiste.setText("Código inválido.");
        lblCodigoExiste.setForeground(Color.red);
        lblCpfExiste.setText("CPF inválido.");
        lblCpfExiste.setForeground(Color.red);
        txtfDataAdmissao.setText(control.Datas.getDiaHoje());
        codCadastrado = false;
        cpfCadastrado = false;
    }

    public void popularExibicaoPessoa(PessoaFisica pf) {
        txtCep.setText(pf.getPessoa().getEndereco().getCep());
        txtNomePessoa.setText(pf.getPessoa().getNome());
        txtLogradouro.setText(pf.getPessoa().getEndereco().getLogradouro());
        txtCidade.setText(pf.getPessoa().getEndereco().getCidade());
        txtEstado.setText(pf.getPessoa().getEndereco().getEstado());
        txtBairro.setText(pf.getPessoa().getEndereco().getBairro());
        txtNumero.setText(pf.getPessoa().getComplementoLogradouro());
        txtTelefone.setText("" + pf.getPessoa().getTelefone());
        txtCelular.setText("" + pf.getCelular());
        if (pf.getSexoBanco() == 0) {
            lblSexoValor.setText("Masculino");
        } else {
            lblSexoValor.setText("Feminino");
        }

    }

    public void limparExibicaoPessoa() {
        txtCep.setText("");
        txtNomePessoa.setText("");
        txtLogradouro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtBairro.setText("");
        txtNumero.setText("");
        txtTelefone.setText("");
        txtCelular.setText("");
        lblSexoValor.setText("-");

    }

    private void iniciarlizarTabela() {
        String[] nomeColunas = {"Código", "CEP", "Nome", "CPF", "Sexo", "Telefone", "Celular", "Nº Logradouro",
            "Salário", "Cargo", "Admissão", "Horas Trabalhadas", "Nível Administrativo"};
        try {
            DefaultTableModel model = new DefaultTableModel();
            tblFuncionarioRecente.setModel(model);
            model.setColumnIdentifiers(nomeColunas);
            model.setRowCount(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao popular tabela.\n\n" + ex.getMessage(), "Erro de população de tabela", 0);
        }

    }

    private void atualizarTabela(Funcionario func) {
        Object rowData[] = new Object[13];

        rowData[0] = func.getCodigoFuncionario();
        rowData[1] = func.getPessoa().getEndereco().getCep();
        rowData[2] = func.getPessoa().getNome();
        rowData[3] = func.getFisica().getCpf();
        rowData[4] = func.getFisica().getSexoSTR();
        rowData[5] = func.getPessoa().getTelefone();
        rowData[6] = func.getFisica().getCelular();
        rowData[7] = func.getPessoa().getComplementoLogradouro();
        rowData[8] = func.getSalarioSTR();
        rowData[9] = func.getCargo();
        rowData[10] = func.getDataContrato();
        rowData[11] = func.getHorasTrabalhadas();
        rowData[12] = func.getNivelAdministrativo();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblFuncionarioRecente.getModel();
        model.addRow(rowData);
    }

    private void selecionarAoFocar() {
        //Código para selecionar o texto todo ao ganhar foco
        txtfSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfSalario.selectAll();
                    }
                });
            }
        });

        txtfDataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfDataAdmissao.selectAll();
                    }
                });
            }
        });

        txtfHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfHoras.selectAll();
                    }
                });
            }
        });
    }

    private void verificarCpfExiste() {
        if ((txtCpf.getText().length() < 11) || (txtCpf.getText().length() > 11)) {
            lblCpfExiste.setText("CPF Inválido.");
            lblCpfExiste.setForeground(Color.red);
            cpfCadastrado = false;
            limparExibicaoPessoa();
        } else {
            cpfCadastrado = dao.DaoPessoa.existePessoaFisica(txtCpf.getText());
            if (cpfCadastrado) {
                lblCpfExiste.setText("CPF Cadastrado.");
                lblCpfExiste.setForeground(Color.black);
                pessoaFisicaExibicao = dao.DaoPessoa.popularPessoaFisica(txtCpf.getText());
                popularExibicaoPessoa(pessoaFisicaExibicao);
            } else {
                lblCpfExiste.setText("CPF Inexistente.");
                lblCpfExiste.setForeground(Color.red);
                limparExibicaoPessoa();
            }
        }
    }

    private boolean validarCampos() {
        if (txtCodigoFuncionario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Código de Funcionário em branco.\n\n"
                    + "Digite o Código de Funcionário corretamente.", "Erro - Código de Funcionário inválido", 0);
            txtCodigoFuncionario.requestFocus();
            return false;
        } else if (!codCadastrado) {
            JOptionPane.showMessageDialog(null, "Código de Funcionário inválido.\n\n"
                    + "O Código não existe ou já está cadastrado. Informe um código diferente.", "Erro - Código de Funcionário inválido", 0);
            txtCodigoFuncionario.requestFocus();
            return false;
        } else if (txtCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CPF em branco.\n\n"
                    + "Digite o CPF corretamente, com 11 dígitos, sem hífens ou pontos.", "Erro - CPF inválido", 0);
            txtCpf.requestFocus();
            return false;
        } else if (txtCpf.getText().length() < 11) {
            JOptionPane.showMessageDialog(null, "CPF em Inválido.\n\n"
                    + "Digite o CPF corretamente, com 11 dígitos, sem hífens ou pontos.", "Erro - CPF inválido", 0);
            txtCpf.requestFocus();
            return false;
        } else if (!cpfCadastrado) {
            JOptionPane.showMessageDialog(null, "CPF em Inválido.\n\n"
                    + "O CPF informado não está cadastrado. Digite um CPF diferente, com 11 dígitos, sem hífens ou pontos.", "Erro - CPF inválido", 0);
            txtCpf.requestFocus();
            return false;
        } else if (txtCargo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cargo em branco.\n\n"
                    + "Digite o Cargo a ser exercido pelo funcionário(a)", "Erro - Cargo Inválido", 0);
            txtCargo.requestFocus();
            return false;
        } else if (txtfDataAdmissao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data de Admissão em branco.\n\n"
                    + "Informe a data de Admissão corretamente. Clique em 'Hoje' para definir como a data atual.", "Erro - Data Inválida", 0);
            txtfDataAdmissao.requestFocus();
            return false;
        } else if (txtfSalario.getText().equals("0,00")) {
            JOptionPane.showMessageDialog(null, "Salário zerado.\n\n"
                    + "Digite o Salário corretamente.", "Erro - Salário inválido", 0);
            txtfSalario.requestFocus();
            return false;
        } else if (txtfHoras.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Horas mensais zerada.\n\n"
                    + "Digite as Horas Mensais corretamente.", "Erro - Horas Mensais inválida", 0);
            txtfHoras.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private void verificarCodigoFuncionario() {
        if (txtCodigoFuncionario.getText().length() < 1) {
            lblCodigoExiste.setText("Código inválido.");
            lblCodigoExiste.setForeground(Color.red);
            codCadastrado = false;
        } else if (dao.DaoFuncionario.existeFuncionario(txtCodigoFuncionario.getText())) {
            lblCodigoExiste.setText("Funcionário já cadastrado.");
            lblCodigoExiste.setForeground(Color.red);
            codCadastrado = false;
        } else {
            lblCodigoExiste.setText("Código de Funcionário livre.");
            lblCodigoExiste.setForeground(Color.black);
            codCadastrado = true;
        }
    }

    private void cadastrarFuncionario() {
        PessoaFisica pf = new PessoaFisica();
        if (validarCampos()) {
            pf = DaoPessoa.popularPessoaFisica(txtCpf.getText());
            Funcionario func = new Funcionario(txtCodigoFuncionario.getText(),
                    pf.getPessoa(), pf, txtfSalario.getText(), txtCargo.getText(),
                    txtfDataAdmissao.getText(), txtfDataAdmissao.getText(), txtfHoras.getText(),
                    rbtVisualizacao.isSelected());
            boolean cadastroSucedido = dao.DaoFuncionario.cadastrarFuncionario(func);
            if (cadastroSucedido) {
                atualizarTabela(func);
            }
        }
    }
}
