/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Datas;
import control.TextSize;
import dao.DaoPessoa;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.Endereco;
import model.Funcionario;
import model.Pessoa;
import model.PessoaFisica;

/**
 *
 * @author Luiz
 */
public class FrmCadastroFuncionario extends javax.swing.JFrame {

    private boolean codCadastrado;
    private boolean cpfCadastrado;
    Endereco endExibicao;
    PessoaFisica pessoaFisicaExibicao;
    Pessoa pessoaExibicao;

    /**
     * Creates new form FrmCadastroPeca
     */
    public FrmCadastroFuncionario(int nvlAdm) {
        initComponents();
        this.endExibicao = new Endereco();
        this.pessoaFisicaExibicao = new PessoaFisica();
        this.pessoaExibicao = new Pessoa();

        MaskFormatter dateMask;
        try {
            dateMask = new MaskFormatter("##/##/####");
            dateMask.setPlaceholderCharacter('*');
            dateMask.install(txtfDataAdmissao);
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastroDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtfDataAdmissao.setText(Datas.getDiaHoje());
        iniciarlizarTabela();
        if (nvlAdm == 0) {
            btnCadastrar.setEnabled(false);
        }

        selecionarAoFocar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoNivelADM = new javax.swing.ButtonGroup();
        grupoSexoExib = new javax.swing.ButtonGroup();
        panPrincipal = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        lblCodigoFuncionario = new javax.swing.JLabel();
        txtCodigoFuncionario = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnListarFuncionarios = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblHorasTrabalhadas = new javax.swing.JLabel();
        lblNivelAdm = new javax.swing.JLabel();
        rbtVisualizacao = new javax.swing.JRadioButton();
        rbtCompleto = new javax.swing.JRadioButton();
        lblCpfExiste = new javax.swing.JLabel();
        btnCadastrarPessoa = new javax.swing.JButton();
        panDadosPessoa = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNomePessoa = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        lblLogradouro = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        Bairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        Bairro1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        lblSexoDesc = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblSexoValor = new javax.swing.JLabel();
        lblCodigoExiste = new javax.swing.JLabel();
        txtfSalario = new javax.swing.JFormattedTextField();
        txtfHoras = new javax.swing.JFormattedTextField();
        lblDataAdmissao = new javax.swing.JLabel();
        txtfDataAdmissao = new javax.swing.JFormattedTextField();
        btnHoje = new javax.swing.JButton();
        btnMenuPrincipal1 = new javax.swing.JButton();
        btnFecharFrame1 = new javax.swing.JButton();
        lblFuncionarioRecente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarioRecente = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logopng32.png")));
        setMinimumSize(new java.awt.Dimension(1152, 648));
        setResizable(false);
        setSize(new java.awt.Dimension(1152, 648));
        getContentPane().setLayout(null);

        panPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        panPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1152, 648));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1152, 648));
        panPrincipal.setOpaque(false);
        panPrincipal.setPreferredSize(new java.awt.Dimension(1152, 648));
        panPrincipal.setLayout(null);

        lblCpf.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCpf.setText("CPF:");
        panPrincipal.add(lblCpf);
        lblCpf.setBounds(646, 10, 34, 25);

        txtCpf.setNextFocusableComponent(txtCargo);
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });
        panPrincipal.add(txtCpf);
        txtCpf.setBounds(691, 10, 90, 25);

        lblSalario.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblSalario.setText("Salário:");
        panPrincipal.add(lblSalario);
        lblSalario.setBounds(785, 50, 57, 25);

        lblCodigoFuncionario.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCodigoFuncionario.setText("Código do Funcionário:");
        panPrincipal.add(lblCodigoFuncionario);
        lblCodigoFuncionario.setBounds(12, 10, 190, 25);

        txtCodigoFuncionario.setNextFocusableComponent(txtCpf);
        txtCodigoFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoFuncionarioKeyReleased(evt);
            }
        });
        panPrincipal.add(txtCodigoFuncionario);
        txtCodigoFuncionario.setBounds(206, 10, 110, 25);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        panPrincipal.add(btnLimpar);
        btnLimpar.setBounds(795, 87, 100, 30);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setNextFocusableComponent(txtCodigoFuncionario);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCadastrar);
        btnCadastrar.setBounds(927, 87, 130, 30);

        btnListarFuncionarios.setText("Listar Funcionários");
        btnListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFuncionariosActionPerformed(evt);
            }
        });
        panPrincipal.add(btnListarFuncionarios);
        btnListarFuncionarios.setBounds(477, 8, 121, 30);

        lblCargo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCargo.setText("Cargo a ser exercido:");
        panPrincipal.add(lblCargo);
        lblCargo.setBounds(13, 50, 172, 25);

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCargoKeyReleased(evt);
            }
        });
        panPrincipal.add(txtCargo);
        txtCargo.setBounds(206, 50, 260, 25);

        lblHorasTrabalhadas.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblHorasTrabalhadas.setText("Horas Mensais:");
        panPrincipal.add(lblHorasTrabalhadas);
        lblHorasTrabalhadas.setBounds(923, 50, 123, 25);

        lblNivelAdm.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblNivelAdm.setText("Nível Administrativo do Sistema:");
        panPrincipal.add(lblNivelAdm);
        lblNivelAdm.setBounds(12, 90, 270, 25);

        grupoNivelADM.add(rbtVisualizacao);
        rbtVisualizacao.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        rbtVisualizacao.setSelected(true);
        rbtVisualizacao.setText("Visualização");
        rbtVisualizacao.setOpaque(false);
        rbtVisualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVisualizacaoActionPerformed(evt);
            }
        });
        panPrincipal.add(rbtVisualizacao);
        rbtVisualizacao.setBounds(288, 90, 121, 25);

        grupoNivelADM.add(rbtCompleto);
        rbtCompleto.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        rbtCompleto.setText("Completo");
        rbtCompleto.setOpaque(false);
        rbtCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCompletoActionPerformed(evt);
            }
        });
        panPrincipal.add(rbtCompleto);
        rbtCompleto.setBounds(419, 90, 105, 25);

        lblCpfExiste.setForeground(java.awt.Color.red);
        lblCpfExiste.setText("CPF Inválido.");
        panPrincipal.add(lblCpfExiste);
        lblCpfExiste.setBounds(785, 10, 153, 25);

        btnCadastrarPessoa.setText("Cadastrar CPF");
        btnCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPessoaActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCadastrarPessoa);
        btnCadastrarPessoa.setBounds(956, 8, 103, 29);

        panDadosPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Pessoa"));
        panDadosPessoa.setOpaque(false);
        panDadosPessoa.setLayout(null);

        lblNome.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblNome.setText("Nome:");
        panDadosPessoa.add(lblNome);
        lblNome.setBounds(10, 20, 140, 25);

        txtNomePessoa.setEditable(false);
        txtNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePessoaActionPerformed(evt);
            }
        });
        panDadosPessoa.add(txtNomePessoa);
        txtNomePessoa.setBounds(162, 20, 316, 25);

        lblTelefone.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone:");
        panDadosPessoa.add(lblTelefone);
        lblTelefone.setBounds(10, 140, 140, 25);

        txtTelefone.setEditable(false);
        panDadosPessoa.add(txtTelefone);
        txtTelefone.setBounds(162, 140, 316, 25);

        lblCelular.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCelular.setText("Celular:");
        panDadosPessoa.add(lblCelular);
        lblCelular.setBounds(540, 140, 140, 25);

        lblLogradouro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblLogradouro.setText("Logradouro:");
        panDadosPessoa.add(lblLogradouro);
        lblLogradouro.setBounds(540, 60, 140, 25);

        txtLogradouro.setEditable(false);
        panDadosPessoa.add(txtLogradouro);
        txtLogradouro.setBounds(710, 60, 316, 25);

        lblCidade.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCidade.setText("Cidade:");
        panDadosPessoa.add(lblCidade);
        lblCidade.setBounds(10, 60, 140, 25);

        txtCidade.setEditable(false);
        panDadosPessoa.add(txtCidade);
        txtCidade.setBounds(162, 60, 114, 25);

        lblEstado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblEstado.setText("Estado:");
        panDadosPessoa.add(lblEstado);
        lblEstado.setBounds(280, 60, 73, 25);

        txtEstado.setEditable(false);
        panDadosPessoa.add(txtEstado);
        txtEstado.setBounds(357, 60, 121, 25);

        Bairro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        Bairro.setText("Bairro:");
        panDadosPessoa.add(Bairro);
        Bairro.setBounds(10, 100, 130, 25);

        txtBairro.setEditable(false);
        panDadosPessoa.add(txtBairro);
        txtBairro.setBounds(162, 100, 114, 25);

        Bairro1.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        Bairro1.setText("N° Logradouro:");
        panDadosPessoa.add(Bairro1);
        Bairro1.setBounds(280, 100, 127, 25);

        txtNumero.setEditable(false);
        panDadosPessoa.add(txtNumero);
        txtNumero.setBounds(417, 100, 61, 25);

        txtCelular.setEditable(false);
        panDadosPessoa.add(txtCelular);
        txtCelular.setBounds(710, 140, 316, 25);

        lblSexoDesc.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblSexoDesc.setText("Sexo:");
        panDadosPessoa.add(lblSexoDesc);
        lblSexoDesc.setBounds(540, 100, 140, 25);

        lblCep.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCep.setText("CEP:");
        panDadosPessoa.add(lblCep);
        lblCep.setBounds(540, 20, 140, 25);

        txtCep.setEditable(false);
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });
        panDadosPessoa.add(txtCep);
        txtCep.setBounds(710, 20, 178, 25);

        lblSexoValor.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblSexoValor.setText("-");
        panDadosPessoa.add(lblSexoValor);
        lblSexoValor.setBounds(710, 100, 180, 25);

        panPrincipal.add(panDadosPessoa);
        panDadosPessoa.setBounds(12, 123, 1090, 180);

        lblCodigoExiste.setForeground(java.awt.Color.red);
        lblCodigoExiste.setText("Código inválido.");
        panPrincipal.add(lblCodigoExiste);
        lblCodigoExiste.setBounds(320, 10, 151, 25);

        txtfSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtfSalario.setText("0,00");
        txtfSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfSalarioMouseClicked(evt);
            }
        });
        txtfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfSalarioKeyReleased(evt);
            }
        });
        panPrincipal.add(txtfSalario);
        txtfSalario.setBounds(846, 50, 67, 25);

        txtfHoras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtfHoras.setText("0");
        txtfHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfHorasKeyReleased(evt);
            }
        });
        panPrincipal.add(txtfHoras);
        txtfHoras.setBounds(1050, 50, 40, 25);

        lblDataAdmissao.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDataAdmissao.setText("Data Admissão:");
        panPrincipal.add(lblDataAdmissao);
        lblDataAdmissao.setBounds(470, 50, 126, 25);

        txtfDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        panPrincipal.add(txtfDataAdmissao);
        txtfDataAdmissao.setBounds(603, 50, 113, 25);

        btnHoje.setText("Hoje");
        btnHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHojeActionPerformed(evt);
            }
        });
        panPrincipal.add(btnHoje);
        btnHoje.setBounds(726, 50, 55, 25);

        getContentPane().add(panPrincipal);
        panPrincipal.setBounds(10, 10, 1125, 310);

        btnMenuPrincipal1.setText("Menu Principal");
        btnMenuPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipal1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal1);
        btnMenuPrincipal1.setBounds(900, 550, 130, 30);

        btnFecharFrame1.setText("Fechar ");
        btnFecharFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFrame1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecharFrame1);
        btnFecharFrame1.setBounds(1055, 550, 80, 30);

        lblFuncionarioRecente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblFuncionarioRecente.setText("Funcionários Cadastrados Recentemente:");
        getContentPane().add(lblFuncionarioRecente);
        lblFuncionarioRecente.setBounds(10, 320, 350, 25);

        tblFuncionarioRecente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarioRecente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 1125, 190);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, -20, 1150, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipal1ActionPerformed
        control.Janelas.focarPrincipal();
    }//GEN-LAST:event_btnMenuPrincipal1ActionPerformed

    private void btnFecharFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFrame1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharFrame1ActionPerformed

    private void txtfHorasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfHorasKeyReleased
        txtfHoras.setText(control.TextSize.maxLenghtHoraMensal(txtfHoras.getText()));
    }//GEN-LAST:event_txtfHorasKeyReleased

    private void txtfSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfSalarioKeyReleased
        txtfSalario.setText(control.TextSize.maxLenghtSalario(txtfSalario.getText()));
    }//GEN-LAST:event_txtfSalarioKeyReleased

    private void txtNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePessoaActionPerformed

    private void btnCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPessoaActionPerformed
        control.Janelas.abrirCadastroPessoa();
    }//GEN-LAST:event_btnCadastrarPessoaActionPerformed

    private void rbtCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCompletoActionPerformed

    }//GEN-LAST:event_rbtCompletoActionPerformed

    private void rbtVisualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVisualizacaoActionPerformed

    }//GEN-LAST:event_rbtVisualizacaoActionPerformed

    private void txtCargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyReleased
        txtCargo.setText(TextSize.maxLenghtCargo(txtCargo.getText()));
    }//GEN-LAST:event_txtCargoKeyReleased

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void btnListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFuncionariosActionPerformed
        control.Janelas.abrirListagemFuncionario();
    }//GEN-LAST:event_btnListarFuncionariosActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarFuncionario();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodigoFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioKeyReleased
        txtCodigoFuncionario.setText(TextSize.maxLenghtFuncionario(txtCodigoFuncionario.getText()));
        verificarCodigoFuncionario();
    }//GEN-LAST:event_txtCodigoFuncionarioKeyReleased

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        txtCpf.setText(TextSize.maxLenghtCPFCNPJ(txtCpf.getText(), true));
        verificarCpfExiste();
    }//GEN-LAST:event_txtCpfKeyReleased

    private void btnHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHojeActionPerformed
        txtfDataAdmissao.setText(control.Datas.getDiaHoje());
    }//GEN-LAST:event_btnHojeActionPerformed

    private void txtfSalarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfSalarioMouseClicked
        txtfDataAdmissao.selectAll();
    }//GEN-LAST:event_txtfSalarioMouseClicked

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroFuncionario(control.SynchroSoft.getNvlAdm()).setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JLabel Bairro1;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarPessoa;
    private javax.swing.JButton btnFecharFrame1;
    private javax.swing.JButton btnHoje;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListarFuncionarios;
    private javax.swing.JButton btnMenuPrincipal1;
    private javax.swing.ButtonGroup grupoNivelADM;
    private javax.swing.ButtonGroup grupoSexoExib;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigoExiste;
    private javax.swing.JLabel lblCodigoFuncionario;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpfExiste;
    private javax.swing.JLabel lblDataAdmissao;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFuncionarioRecente;
    private javax.swing.JLabel lblHorasTrabalhadas;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNivelAdm;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSexoDesc;
    private javax.swing.JLabel lblSexoValor;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel panDadosPessoa;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JRadioButton rbtCompleto;
    private javax.swing.JRadioButton rbtVisualizacao;
    private javax.swing.JTable tblFuncionarioRecente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNomePessoa;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JFormattedTextField txtfDataAdmissao;
    private javax.swing.JFormattedTextField txtfHoras;
    private javax.swing.JFormattedTextField txtfSalario;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        txtCodigoFuncionario.setText("");
        txtCpf.setText("");
        txtCargo.setText("");
        txtfSalario.setText("0,00");
        txtfHoras.setText("0");
        rbtVisualizacao.setSelected(true);
        limparExibicaoPessoa();
        lblCodigoExiste.setText("Código inválido.");
        lblCodigoExiste.setForeground(Color.red);
        lblCpfExiste.setText("CPF inválido.");
        lblCpfExiste.setForeground(Color.red);
        txtfDataAdmissao.setText(control.Datas.getDiaHoje());
        codCadastrado = false;
        cpfCadastrado = false;
    }

    public void popularExibicaoPessoa(PessoaFisica pf) {
        txtCep.setText(pf.getPessoa().getEndereco().getCep());
        txtNomePessoa.setText(pf.getPessoa().getNome());
        txtLogradouro.setText(pf.getPessoa().getEndereco().getLogradouro());
        txtCidade.setText(pf.getPessoa().getEndereco().getCidade());
        txtEstado.setText(pf.getPessoa().getEndereco().getEstado());
        txtBairro.setText(pf.getPessoa().getEndereco().getBairro());
        txtNumero.setText(pf.getPessoa().getComplementoLogradouro());
        txtTelefone.setText("" + pf.getPessoa().getTelefone());
        txtCelular.setText("" + pf.getCelular());
        if (pf.getSexoBanco() == 0) {
            lblSexoValor.setText("Masculino");
        } else {
            lblSexoValor.setText("Feminino");
        }

    }

    public void limparExibicaoPessoa() {
        txtCep.setText("");
        txtNomePessoa.setText("");
        txtLogradouro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtBairro.setText("");
        txtNumero.setText("");
        txtTelefone.setText("");
        txtCelular.setText("");
        lblSexoValor.setText("-");

    }

    private void iniciarlizarTabela() {
        String[] nomeColunas = {"Código", "CEP", "Nome", "CPF", "Sexo", "Telefone", "Celular", "Nº Logradouro",
            "Salário", "Cargo", "Admissão", "Horas Trabalhadas", "Nível Administrativo", "Efetivado"};
        try {
            DefaultTableModel model = new DefaultTableModel();
            tblFuncionarioRecente.setModel(model);
            model.setColumnIdentifiers(nomeColunas);
            model.setRowCount(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao popular tabela.\n\n" + ex.getMessage(), "Erro de população de tabela", 0);
        }

    }

    private void atualizarTabela(Funcionario func) {
        Object rowData[] = new Object[14];

        rowData[0] = func.getCodigoFuncionario();
        rowData[1] = func.getPessoa().getEndereco().getCep();
        rowData[2] = func.getPessoa().getNome();
        rowData[3] = func.getFisica().getCpf();
        rowData[4] = func.getFisica().getSexoSTR();
        rowData[5] = func.getPessoa().getTelefone();
        rowData[6] = func.getFisica().getCelular();
        rowData[7] = func.getPessoa().getComplementoLogradouro();
        rowData[8] = func.getSalarioSTR();
        rowData[9] = func.getCargo();
        rowData[10] = func.getDataContrato();
        rowData[11] = func.getHorasTrabalhadas();
        rowData[12] = func.getNivelAdministrativo();
        rowData[13] = func.getEfetivadoSTR();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblFuncionarioRecente.getModel();
        model.addRow(rowData);
    }

    private void selecionarAoFocar() {
        //Código para selecionar o texto todo ao ganhar foco
        txtfSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfSalario.selectAll();
                    }
                });
            }
        });

        txtfDataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfDataAdmissao.selectAll();
                    }
                });
            }
        });

        txtfHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfHoras.selectAll();
                    }
                });
            }
        });
    }

    private void verificarCpfExiste() {
        if ((txtCpf.getText().length() < 11) || (txtCpf.getText().length() > 11)) {
            lblCpfExiste.setText("CPF Inválido.");
            lblCpfExiste.setForeground(Color.red);
            cpfCadastrado = false;
            limparExibicaoPessoa();
        } else {
            cpfCadastrado = dao.DaoPessoa.existePessoaFisica(txtCpf.getText());
            if (cpfCadastrado) {
                lblCpfExiste.setText("CPF Cadastrado.");
                lblCpfExiste.setForeground(Color.black);
                pessoaFisicaExibicao = dao.DaoPessoa.popularPessoaFisica(txtCpf.getText());
                popularExibicaoPessoa(pessoaFisicaExibicao);
            } else {
                lblCpfExiste.setText("CPF Inexistente.");
                lblCpfExiste.setForeground(Color.red);
                limparExibicaoPessoa();
            }
        }
    }

    private boolean validarCampos() {
        if (txtCodigoFuncionario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Código de Funcionário em branco.\n\n"
                    + "Digite o Código de Funcionário corretamente.", "Erro - Código de Funcionário inválido", 0);
            txtCodigoFuncionario.requestFocus();
            return false;
        } else if (!codCadastrado) {
            JOptionPane.showMessageDialog(null, "Código de Funcionário inválido.\n\n"
                    + "O Código não existe ou já está cadastrado. Informe um código diferente.", "Erro - Código de Funcionário inválido", 0);
            txtCodigoFuncionario.requestFocus();
            return false;
        } else if (txtCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CPF em branco.\n\n"
                    + "Digite o CPF corretamente, com 11 dígitos, sem hífens ou pontos.", "Erro - CPF inválido", 0);
            txtCpf.requestFocus();
            return false;
        } else if (txtCpf.getText().length() < 11) {
            JOptionPane.showMessageDialog(null, "CPF em Inválido.\n\n"
                    + "Digite o CPF corretamente, com 11 dígitos, sem hífens ou pontos.", "Erro - CPF inválido", 0);
            txtCpf.requestFocus();
            return false;
        } else if (!cpfCadastrado) {
            JOptionPane.showMessageDialog(null, "CPF em Inválido.\n\n"
                    + "O CPF informado não está cadastrado. Digite um CPF diferente, com 11 dígitos, sem hífens ou pontos.", "Erro - CPF inválido", 0);
            txtCpf.requestFocus();
            return false;
        } else if (txtCargo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cargo em branco.\n\n"
                    + "Digite o Cargo a ser exercido pelo funcionário(a)", "Erro - Cargo Inválido", 0);
            txtCargo.requestFocus();
            return false;
        } else if (txtfDataAdmissao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data de Admissão em branco.\n\n"
                    + "Informe a data de Admissão corretamente. Clique em 'Hoje' para definir como a data atual.", "Erro - Data Inválida", 0);
            txtfDataAdmissao.requestFocus();
            return false;
        } else if (txtfSalario.getText().equals("0,00")) {
            JOptionPane.showMessageDialog(null, "Salário zerado.\n\n"
                    + "Digite o Salário corretamente.", "Erro - Salário inválido", 0);
            txtfSalario.requestFocus();
            return false;
        } else if (txtfHoras.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Horas mensais zerada.\n\n"
                    + "Digite as Horas Mensais corretamente.", "Erro - Horas Mensais inválida", 0);
            txtfHoras.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private void verificarCodigoFuncionario() {
        if (txtCodigoFuncionario.getText().length() < 1) {
            lblCodigoExiste.setText("Código inválido.");
            lblCodigoExiste.setForeground(Color.red);
            codCadastrado = false;
        } else if (dao.DaoFuncionario.existeFuncionario(txtCodigoFuncionario.getText())) {
            lblCodigoExiste.setText("Funcionário já cadastrado.");
            lblCodigoExiste.setForeground(Color.red);
            codCadastrado = false;
        } else {
            lblCodigoExiste.setText("Código de Funcionário livre.");
            lblCodigoExiste.setForeground(Color.black);
            codCadastrado = true;
        }
    }

    private void cadastrarFuncionario() {
        PessoaFisica pf = new PessoaFisica();
        if (validarCampos()) {
            pf = DaoPessoa.popularPessoaFisica(txtCpf.getText());
            Funcionario func = new Funcionario(txtCodigoFuncionario.getText(),
                    pf.getPessoa(), pf, txtfSalario.getText(), txtCargo.getText(),
                    txtfDataAdmissao.getText(), txtfDataAdmissao.getText(), txtfHoras.getText(),
                    rbtVisualizacao.isSelected());
            func.setEfetivadoBooleano(true);
            boolean cadastroSucedido = dao.DaoFuncionario.cadastrarFuncionario(func);
            if (cadastroSucedido) {
                atualizarTabela(func);
            }
        }
    }
}
