/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TextSize;
import dao.DaoPessoa;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Endereco;
import model.PessoaJuridica;
import model.Pessoa;

/**
 *
 * @author Luiz
 */
public class FrmListagemPessoaJ extends javax.swing.JFrame {
    
    private boolean cepCadastrado;
    private boolean ultimoTipoPesquisa;
    private boolean existeCnpj;
    private String PK_REF;
    
    /**
     * Creates new form FrmListagemPessoa
     */
    public FrmListagemPessoaJ(int nvlAdm) {
        initComponents();
        inicializarTabela();
        txtfDataDe.setText(control.Datas.getDiaHoje());
        txtfDataAte.setText(control.Datas.getDiaHoje());
        selecionarAoFocar();
        modoPesquisaNormal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPesquisar = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        panPrincipal1 = new javax.swing.JPanel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblNumeroLogradouro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNomePessoaFicticio = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblCepExiste = new javax.swing.JLabel();
        btnCadastrarCep = new javax.swing.JButton();
        txtNumeroLogradouro = new javax.swing.JTextField();
        lblTipoPessoa1 = new javax.swing.JLabel();
        rbtSimCadastro = new javax.swing.JRadioButton();
        rbtNaoCadastro = new javax.swing.JRadioButton();
        lblCpfCnpj = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        lblCelRamal = new javax.swing.JLabel();
        txtCelRamal = new javax.swing.JTextField();
        lblDataCadastro = new javax.swing.JLabel();
        txtfDataCadastro = new javax.swing.JFormattedTextField();
        btnHoje = new javax.swing.JButton();
        lblCpfCnpjExiste = new javax.swing.JLabel();
        txtfCep = new javax.swing.JFormattedTextField();
        txtCpfCnpj = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();
        btnLimparTabela = new javax.swing.JButton();
        btnListarTodos = new javax.swing.JButton();
        btnCadastrarCnpj = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblDigiteODado = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        txtfDataDe = new javax.swing.JFormattedTextField();
        btnHojePesquisa = new javax.swing.JButton();
        lblDataAte = new javax.swing.JLabel();
        txtfDataAte = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagemPessoaJ = new javax.swing.JTable();
        btnDeletarTodosRegistros = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnFecharFrame = new javax.swing.JButton();
        lblPessoaJEncontrado = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Pessoas Jurídicas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logopng32.png")));
        setMaximumSize(new java.awt.Dimension(1152, 648));
        setMinimumSize(new java.awt.Dimension(1152, 648));
        setResizable(false);
        setSize(new java.awt.Dimension(1152, 648));
        getContentPane().setLayout(null);

        panPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panPrincipal.setOpaque(false);
        panPrincipal.setLayout(null);

        lblPesquisar.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblPesquisar.setText("Pesquisar por: ");
        panPrincipal.add(lblPesquisar);
        lblPesquisar.setBounds(10, 10, 120, 25);

        cmbFiltro.setMaximumRowCount(15);
        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome Fictício", "CNPJ", "Razão Social", "CEP", "Logradouro", "Nr Logradouro", "Telefone", "Ramal", "Mantém Contrato?", "Data de Cadastro", "Data Entre/Até" }));
        cmbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroActionPerformed(evt);
            }
        });
        panPrincipal.add(cmbFiltro);
        cmbFiltro.setBounds(160, 10, 210, 25);

        panPrincipal1.setBackground(new java.awt.Color(204, 204, 204));
        panPrincipal1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Pessoa Jurídica"));
        panPrincipal1.setOpaque(false);
        panPrincipal1.setLayout(null);

        lblTelefone.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone:");
        panPrincipal1.add(lblTelefone);
        lblTelefone.setBounds(10, 130, 140, 25);

        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtTelefone);
        txtTelefone.setBounds(150, 130, 316, 25);

        lblNumeroLogradouro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblNumeroLogradouro.setText("Nº Logradouro:");
        panPrincipal1.add(lblNumeroLogradouro);
        lblNumeroLogradouro.setBounds(530, 90, 150, 25);

        lblNome.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblNome.setText("Nome Fictício:");
        panPrincipal1.add(lblNome);
        lblNome.setBounds(10, 50, 150, 25);

        txtNomePessoaFicticio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomePessoaFicticioKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtNomePessoaFicticio);
        txtNomePessoaFicticio.setBounds(150, 50, 316, 25);

        lblCep.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCep.setText("CEP:");
        panPrincipal1.add(lblCep);
        lblCep.setBounds(10, 90, 140, 25);

        lblCepExiste.setForeground(java.awt.Color.red);
        lblCepExiste.setText("Cep Inválido.");
        panPrincipal1.add(lblCepExiste);
        lblCepExiste.setBounds(280, 90, 90, 25);

        btnCadastrarCep.setText("Cadastrar");
        btnCadastrarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCepActionPerformed(evt);
            }
        });
        panPrincipal1.add(btnCadastrarCep);
        btnCadastrarCep.setBounds(384, 87, 80, 29);

        txtNumeroLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroLogradouroActionPerformed(evt);
            }
        });
        txtNumeroLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroLogradouroKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtNumeroLogradouro);
        txtNumeroLogradouro.setBounds(680, 90, 120, 25);

        lblTipoPessoa1.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblTipoPessoa1.setText("Possui Contrato:");
        panPrincipal1.add(lblTipoPessoa1);
        lblTipoPessoa1.setBounds(10, 10, 140, 25);

        rbtSimCadastro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        rbtSimCadastro.setText("Sim");
        rbtSimCadastro.setOpaque(false);
        rbtSimCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSimCadastroActionPerformed(evt);
            }
        });
        panPrincipal1.add(rbtSimCadastro);
        rbtSimCadastro.setBounds(148, 10, 55, 25);

        rbtNaoCadastro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        rbtNaoCadastro.setText("Não");
        rbtNaoCadastro.setOpaque(false);
        rbtNaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNaoCadastroActionPerformed(evt);
            }
        });
        panPrincipal1.add(rbtNaoCadastro);
        rbtNaoCadastro.setBounds(210, 10, 59, 25);

        lblCpfCnpj.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCpfCnpj.setText("CNPJ:");
        panPrincipal1.add(lblCpfCnpj);
        lblCpfCnpj.setBounds(530, 50, 140, 25);

        txtRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazaoSocialKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtRazaoSocial);
        txtRazaoSocial.setBounds(150, 170, 316, 25);

        lblRazaoSocial.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblRazaoSocial.setText("Razão Social:");
        panPrincipal1.add(lblRazaoSocial);
        lblRazaoSocial.setBounds(10, 170, 140, 25);

        lblCelRamal.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblCelRamal.setText("Ramal");
        panPrincipal1.add(lblCelRamal);
        lblCelRamal.setBounds(530, 130, 140, 25);

        txtCelRamal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCelRamalKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtCelRamal);
        txtCelRamal.setBounds(680, 130, 316, 25);

        lblDataCadastro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDataCadastro.setText("Data Cadastro:");
        panPrincipal1.add(lblDataCadastro);
        lblDataCadastro.setBounds(530, 10, 118, 25);

        txtfDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        panPrincipal1.add(txtfDataCadastro);
        txtfDataCadastro.setBounds(680, 10, 120, 25);

        btnHoje.setText("Hoje");
        btnHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHojeActionPerformed(evt);
            }
        });
        panPrincipal1.add(btnHoje);
        btnHoje.setBounds(810, 10, 55, 25);

        lblCpfCnpjExiste.setForeground(java.awt.Color.red);
        lblCpfCnpjExiste.setText("CNPJ Inválido.");
        panPrincipal1.add(lblCpfCnpjExiste);
        lblCpfCnpjExiste.setBounds(810, 50, 190, 25);

        try {
            txtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfCepFocusLost(evt);
            }
        });
        txtfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfCepKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtfCep);
        txtfCep.setBounds(150, 90, 127, 25);

        txtCpfCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfCnpjFocusLost(evt);
            }
        });
        txtCpfCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfCnpjKeyReleased(evt);
            }
        });
        panPrincipal1.add(txtCpfCnpj);
        txtCpfCnpj.setBounds(680, 50, 120, 25);

        panPrincipal.add(panPrincipal1);
        panPrincipal1.setBounds(10, 50, 1100, 210);

        btnDeletar.setText("Deletar registro selecionado");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnDeletar);
        btnDeletar.setBounds(10, 270, 170, 30);

        btnLimparTabela.setText("Limpar tabela");
        btnLimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabelaActionPerformed(evt);
            }
        });
        panPrincipal.add(btnLimparTabela);
        btnLimparTabela.setBounds(410, 270, 120, 30);

        btnListarTodos.setText("Listar todos os registros");
        btnListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodosActionPerformed(evt);
            }
        });
        panPrincipal.add(btnListarTodos);
        btnListarTodos.setBounds(550, 270, 147, 30);

        btnCadastrarCnpj.setText("Cadastrar novo CNPJ");
        btnCadastrarCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCnpjActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCadastrarCnpj);
        btnCadastrarCnpj.setBounds(720, 270, 150, 30);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnAlterar);
        btnAlterar.setBounds(980, 270, 130, 30);

        lblDigiteODado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDigiteODado.setText("Digite o(a) Nome Fictício:");
        lblDigiteODado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblDigiteODadoKeyReleased(evt);
            }
        });
        panPrincipal.add(lblDigiteODado);
        lblDigiteODado.setBounds(375, 10, 280, 25);

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        panPrincipal.add(txtPesquisa);
        txtPesquisa.setBounds(620, 10, 60, 25);

        txtfDataDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtfDataDe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfDataDeKeyReleased(evt);
            }
        });
        panPrincipal.add(txtfDataDe);
        txtfDataDe.setBounds(620, 10, 100, 25);

        btnHojePesquisa.setText("Hoje");
        btnHojePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHojePesquisaActionPerformed(evt);
            }
        });
        panPrincipal.add(btnHojePesquisa);
        btnHojePesquisa.setBounds(730, 10, 55, 25);

        lblDataAte.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblDataAte.setText("Até:");
        panPrincipal.add(lblDataAte);
        lblDataAte.setBounds(800, 10, 34, 25);

        txtfDataAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtfDataAte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfDataAteKeyReleased(evt);
            }
        });
        panPrincipal.add(txtfDataAte);
        txtfDataAte.setBounds(840, 10, 100, 25);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnPesquisar);
        btnPesquisar.setBounds(950, 10, 79, 25);

        getContentPane().add(panPrincipal);
        panPrincipal.setBounds(10, 10, 1125, 310);

        tblListagemPessoaJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListagemPessoaJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemPessoaJMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagemPessoaJ);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 1125, 190);

        btnDeletarTodosRegistros.setText("Deletar todos os registros");
        btnDeletarTodosRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTodosRegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarTodosRegistros);
        btnDeletarTodosRegistros.setBounds(10, 550, 160, 30);

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal);
        btnMenuPrincipal.setBounds(900, 550, 130, 30);

        btnFecharFrame.setText("Fechar ");
        btnFecharFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFrameActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecharFrame);
        btnFecharFrame.setBounds(1055, 550, 80, 30);

        lblPessoaJEncontrado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lblPessoaJEncontrado.setText("Pessoas Jurídicas encontradas no banco de dados. Para visualizar ou alterar um registro, clique em um registro exibido na tabela.");
        getContentPane().add(lblPessoaJEncontrado);
        lblPessoaJEncontrado.setBounds(10, 320, 1120, 25);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, -20, 1150, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DaoPessoa pessoa = new DaoPessoa();
    private void btnDeletarTodosRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTodosRegistrosActionPerformed
        removerTodosRegistros();
    }//GEN-LAST:event_btnDeletarTodosRegistrosActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        control.Janelas.focarPrincipal();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnFecharFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFrameActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharFrameActionPerformed

    private void txtTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyReleased
        txtTelefone.setText(TextSize.maxLenghtTelefone(txtTelefone.getText()));
    }//GEN-LAST:event_txtTelefoneKeyReleased

    private void txtNomePessoaFicticioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePessoaFicticioKeyReleased
        txtNomePessoaFicticio.setText(TextSize.maxLenghtNomeRazao(txtNomePessoaFicticio.getText()));
    }//GEN-LAST:event_txtNomePessoaFicticioKeyReleased

    private void btnCadastrarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCepActionPerformed
        control.Janelas.abrirCadastroEnderecoParametrizada(txtfCep.getText().replace("-", ""));
    }//GEN-LAST:event_btnCadastrarCepActionPerformed

    private void txtNumeroLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroLogradouroActionPerformed

    }//GEN-LAST:event_txtNumeroLogradouroActionPerformed

    private void txtNumeroLogradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroLogradouroKeyReleased
        txtNumeroLogradouro.setText(TextSize.maxLenghtNrLogradouro(txtNumeroLogradouro.getText()));
    }//GEN-LAST:event_txtNumeroLogradouroKeyReleased

    private void rbtSimCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSimCadastroActionPerformed

    }//GEN-LAST:event_rbtSimCadastroActionPerformed

    private void rbtNaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNaoCadastroActionPerformed

    }//GEN-LAST:event_rbtNaoCadastroActionPerformed

    private void txtRazaoSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazaoSocialKeyReleased
        txtRazaoSocial.setText(TextSize.maxLenghtNomeRazao(txtRazaoSocial.getText()));
    }//GEN-LAST:event_txtRazaoSocialKeyReleased

    private void txtCelRamalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelRamalKeyReleased
        textSizeCelRamal();
    }//GEN-LAST:event_txtCelRamalKeyReleased

    private void btnHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHojeActionPerformed
        txtfDataCadastro.setText(control.Datas.getDiaHoje());
    }//GEN-LAST:event_btnHojeActionPerformed

    private void txtfCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfCepFocusLost
        verificarCep();
    }//GEN-LAST:event_txtfCepFocusLost

    private void txtfCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCepKeyReleased
        verificarCep();
    }//GEN-LAST:event_txtfCepKeyReleased

    private void txtCpfCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfCnpjFocusLost
        textSizeCPFJCNPJ();
    }//GEN-LAST:event_txtCpfCnpjFocusLost

    private void txtCpfCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfCnpjKeyReleased
        textSizeCPFJCNPJ();
    }//GEN-LAST:event_txtCpfCnpjKeyReleased

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        deletarRegistro();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabelaActionPerformed
        limparTabela();
    }//GEN-LAST:event_btnLimparTabelaActionPerformed

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
        atualizarTabela(false);
    }//GEN-LAST:event_btnListarTodosActionPerformed

    private void btnCadastrarCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCnpjActionPerformed
        control.Janelas.abrirCadastroPessoa();
    }//GEN-LAST:event_btnCadastrarCnpjActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarRegistro();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed

    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        limiteDigitosPesquisa(cmbFiltro.getSelectedItem().toString());
        pesquisarFiltrada();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void txtfDataDeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfDataDeKeyReleased
        txtfDataDe.setText(control.TextSize.maxLenghtData(txtfDataDe.getText()));
    }//GEN-LAST:event_txtfDataDeKeyReleased

    private void btnHojePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHojePesquisaActionPerformed
        txtfDataDe.setText(control.Datas.getDiaHoje());
        txtfDataAte.setText(control.Datas.getDiaHoje());
    }//GEN-LAST:event_btnHojePesquisaActionPerformed

    private void txtfDataAteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfDataAteKeyReleased
        txtfDataAte.setText(control.TextSize.maxLenghtData(txtfDataAte.getText()));
    }//GEN-LAST:event_txtfDataAteKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        txtfDataDe.setText(txtfDataDe.getText().trim());
        txtfDataAte.setText(txtfDataAte.getText().trim());
        if (txtfDataDe.getText().length() == 10 && txtfDataAte.getText().length() == 10) {
            atualizarTabela(true);
        } else {
            limparTabela();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cmbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroActionPerformed
        lblDigiteODado.setText("Digite o(a) " + cmbFiltro.getSelectedItem().toString() + ":");
        limiteDigitosPesquisa(cmbFiltro.getSelectedItem().toString());
    }//GEN-LAST:event_cmbFiltroActionPerformed

    private void lblDigiteODadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblDigiteODadoKeyReleased
        limiteDigitosPesquisa(cmbFiltro.getSelectedItem().toString());
        pesquisarFiltrada();
    }//GEN-LAST:event_lblDigiteODadoKeyReleased

    private void tblListagemPessoaJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemPessoaJMouseClicked
        popularCampos();
    }//GEN-LAST:event_tblListagemPessoaJMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListagemPessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListagemPessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListagemPessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListagemPessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListagemPessoaJ(control.SynchroSoft.getNvlAdm()).setVisible(true);
            }
        });
    }  
       
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrarCep;
    private javax.swing.JButton btnCadastrarCnpj;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDeletarTodosRegistros;
    private javax.swing.JButton btnFecharFrame;
    private javax.swing.JButton btnHoje;
    private javax.swing.JButton btnHojePesquisa;
    private javax.swing.JButton btnLimparTabela;
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCelRamal;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCepExiste;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblCpfCnpjExiste;
    private javax.swing.JLabel lblDataAte;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblDigiteODado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumeroLogradouro;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblPessoaJEncontrado;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoPessoa1;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panPrincipal1;
    private javax.swing.JRadioButton rbtNaoCadastro;
    private javax.swing.JRadioButton rbtSimCadastro;
    private javax.swing.JTable tblListagemPessoaJ;
    private javax.swing.JTextField txtCelRamal;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtNomePessoaFicticio;
    private javax.swing.JTextField txtNumeroLogradouro;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JFormattedTextField txtfCep;
    private javax.swing.JFormattedTextField txtfDataAte;
    private javax.swing.JFormattedTextField txtfDataCadastro;
    private javax.swing.JFormattedTextField txtfDataDe;
    // End of variables declaration//GEN-END:variables
    
    private void inicializarTabela() {
        String[] nomeColunas = {"Nome Fictício", "CNPJ", "Razão Social", "CEP", "Logradouro", "Nr Logradouro", "Telefone", "Ramal", "Contrato", "Data de Cadastro"};

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblListagemPessoaJ.setModel(model);
        model.setColumnIdentifiers(nomeColunas);
        model.setRowCount(0);
    }

    
    private void atualizarTabela (boolean filtrada){
       DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblListagemPessoaJ.getModel();
        model.setRowCount(0);

        ArrayList<PessoaJuridica> lista = new ArrayList<>();

        if (filtrada) {
            lista = DaoPessoa.listarPessoaJuridicaFiltrada(String.valueOf(cmbFiltro.getSelectedItem()),
                    txtPesquisa.getText().toLowerCase().trim(), txtfDataDe.getText().toLowerCase().trim(),
                    txtfDataAte.getText().toLowerCase().trim());
            ultimoTipoPesquisa = true;
        } else {
            lista = DaoPessoa.listarPessoaJuridica();
            ultimoTipoPesquisa = false;
        }

        Object dadosLinha[] = new Object[10];

        for (int i = 0; i < lista.size(); i++) {
            dadosLinha[0] = lista.get(i).getPessoa().getNome();
            dadosLinha[1] = lista.get(i).getCnpj();
            dadosLinha[2] = lista.get(i).getRazaoSocial();
            dadosLinha[3] = lista.get(i).getPessoa().getEndereco().getCep();
            dadosLinha[4] = lista.get(i).getPessoa().getEndereco().getLogradouro();
            dadosLinha[5] = lista.get(i).getPessoa().getComplementoLogradouro();
            dadosLinha[6] = lista.get(i).getPessoa().getTelefone();
            dadosLinha[7] = lista.get(i).getRamalCliente();
            dadosLinha[8] = lista.get(i).getPessoa().getManterContratoSTR();
            dadosLinha[9] = lista.get(i).getDataCadastro();
            model.addRow(dadosLinha);
        }
        //String[] nomeColunas = {"Nome Fictício", "CNPJ", "Razão Social", "CEP", "Logradouro", "Nr Logradouro", "Telefone", "Ramal", "Contrato", "Data de Cadastro"};

        limparCampos();
    }
    
    private void modoPesquisaData(boolean fixaOuEntre) {
        boolean dataFixa = false;
        boolean dataEntreAte = true;

        if (fixaOuEntre == dataEntreAte) {
            txtPesquisa.setVisible(false);
            txtfDataDe.setVisible(true);
            txtfDataAte.setVisible(true);
            lblDataAte.setVisible(true);
            btnPesquisar.setVisible(true);
        } else if (fixaOuEntre == dataFixa) {
            txtPesquisa.setVisible(false);
            txtfDataDe.setVisible(true);
            txtfDataAte.setVisible(false);
            lblDataAte.setVisible(false);
            btnPesquisar.setVisible(true);
        }
    }

    private void selecionarAoFocar() {
        //Código para selecionar o texto todo ao ganhar foco
        txtfDataDe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfDataDe.selectAll();
                    }
                });
            }
        });

        txtfDataAte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfDataAte.selectAll();
                    }
                });
            }
        });

        txtfDataCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtfDataCadastro.selectAll();
                    }
                });
            }
        });
    }

    private void modoPesquisaNormal() {
        txtPesquisa.setSize(490, 25);
        txtPesquisa.setVisible(true);
        txtfDataDe.setVisible(false);
        txtfDataAte.setVisible(false);
        lblDataAte.setVisible(false);
        btnPesquisar.setVisible(false);
    }

    private void removerTodosRegistros() {
        int opcao;
        opcao = JOptionPane.showConfirmDialog(this, "Deseja REALMENTE remover todas as pessoas jurídicas do banco de dados?\n\n",
                "Alerta - remoção de todos os registros", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == 0) {
            opcao = JOptionPane.showConfirmDialog(this, "Essa operação tem grandes chances de falhar, devido a existência\n"
                    + "de restrições de chaves estrangeiras no banco de dados.\n\n"
                    + "Deseja REALMENTE tentar excluir todos os registros do banco de dados?\n\n"
                    + "Caso a operação suceda, todos os dados serão permanentemente excluídos.\n"
                    + "Caso ela falhe, talvez alguns registros possam ter sidos excluidos, e outros não."
                    + "\n\n"
                    + "Deseja prosseguir?",
                    "Alerta - remoção de todos os registros", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcao == 0) {
                boolean exclusaoSucedida;
                exclusaoSucedida = dao.DaoPessoa.deletarTodasPessoasJuridicas();
                if (exclusaoSucedida) {
                    atualizarTabela(ultimoTipoPesquisa);
                }
            }
        }
    }

    private void limparCampos() {
        rbtNaoCadastro.setSelected(false);
        rbtSimCadastro.setSelected(false);
        txtfDataCadastro.setText("");
        txtNomePessoaFicticio.setText("");
        txtCpfCnpj.setText("");
        txtfCep.setText("");
        txtNumeroLogradouro.setText("");
        txtTelefone.setText("");
        txtCelRamal.setText("");
        txtRazaoSocial.setText("");
        verificarCep();
        verificarCpfCnpjEmUso();
        PK_REF = null;
    }

    private void verificarCep() {
        String cep = txtfCep.getText();
        cep = cep.replace("-", "");
        cep = cep.trim();
        if ((cep.length() < 8) || (cep.length() > 8)) {
            lblCepExiste.setText("Cep Inválido.");
            lblCepExiste.setForeground(Color.red);
            cepCadastrado = true;
        } else {
            this.cepCadastrado = dao.DaoEndereco.existeEndereco(cep);
            if (cepCadastrado) {
                lblCepExiste.setText("CEP Cadastrado.");
                lblCepExiste.setForeground(Color.black);
                cepCadastrado = false;
            } else {
                lblCepExiste.setText("CEP Inexistente.");
                lblCepExiste.setForeground(Color.red);
                cepCadastrado = true;
            }
        }
    }

    private void verificarCpfCnpjEmUso() {
        if ((txtCpfCnpj.getText().length() < 14) || (txtCpfCnpj.getText().length() > 14)) {
            lblCpfCnpjExiste.setText("CNPJ Inválido.");
            lblCpfCnpjExiste.setForeground(Color.red);
            existeCnpj = true;
        } else {
            this.existeCnpj = dao.DaoPessoa.existePessoaJuridica(txtCpfCnpj.getText());
            if (existeCnpj) {
                lblCpfCnpjExiste.setText("CNPJ já Cadastrado.");
                lblCpfCnpjExiste.setForeground(Color.black);
                existeCnpj = false;
            } else {
                lblCpfCnpjExiste.setText("CNPJ livre.");
                lblCpfCnpjExiste.setForeground(Color.black);
                existeCnpj = false;
            }
        }

    }

    private void textSizeCelRamal() {
        txtCelRamal.setText(TextSize.maxLenghtCelularRamal(txtCelRamal.getText(), false));
    }

    private void textSizeCPFJCNPJ() {
        txtCpfCnpj.setText(TextSize.maxLenghtCPFCNPJ(txtCpfCnpj.getText(), false));
        verificarCpfCnpjEmUso();
    }

    private void deletarRegistro() {
        int opcao;
        String cnpj = ((String) tblListagemPessoaJ.getValueAt(tblListagemPessoaJ.getSelectedRow(), 1));
        opcao = JOptionPane.showConfirmDialog(this, "Atenção! Todos os registros relacionados ao CNPJ "
                + cnpj + " serão permanentemente removidos.\n\nDeseja realmente excluir o registro?",
                "Confirmação de exclusão",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (opcao == 0) {
            dao.DaoPessoa.deletarPessoaJuridica(cnpj);
            atualizarTabela(ultimoTipoPesquisa);
            limparCampos();
        }
    }

    private void limparTabela() {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblListagemPessoaJ.getModel();
        model.setRowCount(0);
        /*
        Chama o metodo limparCampos para limpar os dados do registro anteriormente
        selecionado.
         */
        limparCampos();
    }

    private void alterarRegistro() {
        if (validarCampos()) {
            PessoaJuridica pessoaJuridica = new PessoaJuridica();
            Pessoa pessoa = new Pessoa();
            Endereco endereco = new Endereco();

            String cep = txtfCep.getText();
            cep = cep.replace("-", "");
            cep = cep.trim();

            endereco.setCep(cep);

            pessoa.setManterContrato(rbtSimCadastro.isSelected());
            pessoa.setNome(txtNomePessoaFicticio.getText());
            pessoa.setComplementoLogradouro(txtNumeroLogradouro.getText());
            pessoa.setTelefone(txtTelefone.getText());
            pessoa.setEndereco(endereco);

            pessoaJuridica.setPessoa(pessoa);
            pessoaJuridica.setRazaoSocial(txtRazaoSocial.getText());
            pessoaJuridica.setRamalCliente(txtCelRamal.getText());
            pessoaJuridica.setCnpj(txtCpfCnpj.getText());
            pessoaJuridica.setDataCadastro(txtfDataCadastro.getText());

            boolean alteracaoSucedida;
            alteracaoSucedida = dao.DaoPessoa.alterarPessoaJuridica(pessoaJuridica, PK_REF);

            if (alteracaoSucedida) {
                atualizarTabela(ultimoTipoPesquisa);
                limparCampos();
            }
        }
    }

    private boolean validarCampos() {
        boolean selectionEmpty = tblListagemPessoaJ.getSelectionModel().isSelectionEmpty();
        if (selectionEmpty){
            JOptionPane.showMessageDialog(this, "Nenhum registro selecionado da tabela.\n\n"
                    + "Pesquise por algum registro e clique em alguma linha da tabela.", "Erro - Não há registro selecionado", 0);
            return false;
        } else if (txtNomePessoaFicticio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nome fictício em branco. \nDigite um nome fictício para a pessoa jurídica.", "Erro - Nome Fictício Inválido", 0);
            txtNomePessoaFicticio.requestFocus();
            return false;
        } else if (txtCpfCnpj.getText().length() < 11) {
            JOptionPane.showMessageDialog(null, "CNPJ Inválido. Digite 14 dígitos, sem pontos ou hífens.", "Erro - CNPJ Inválido", 0);
            txtCpfCnpj.requestFocus();
            return false;
        } else if (existeCnpj) {
            JOptionPane.showMessageDialog(null, "CNPJ inválido. Verifique se o CNPJ está correto e se já não existe um mesmo CNPJ cadastrado.", "Erro - CNPJ Inválido", 0);
            txtCpfCnpj.requestFocus();
            return false;
        } else if (cepCadastrado) {
            JOptionPane.showMessageDialog(null, "CEP inválido. Verifique se o CEP informado está correto ou se ele já está cadastrado.", "Erro - CEP Inválido", 0);
            txtfCep.requestFocus();
            return false;
        } else if (txtNumeroLogradouro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Número do logradouro em branco. \nDigite o número e/ou complemento do logradouro.", "Erro - Nº Logradouro Inválido", 0);
            txtNumeroLogradouro.requestFocus();
            return false;
        } else if (txtRazaoSocial.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Razão social em branco. \nDigite a razão social para a pessoa jurídica.", "Erro - Razão Social Inválida", 0);
            txtRazaoSocial.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private void limiteDigitosPesquisa(String filtro) {
        /*
Nome Fictício
CNPJ
Razão Social
CEP
Logradouro
Nr Logradouro
Telefone
Ramal
Mantém Contrato?
Data de Cadastro
Data Entre/Até
*/
        switch (filtro) {
            case "Nome Fictício":
                txtPesquisa.setText(control.TextSize.maxLenghtNomeRazao(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "CNPJ":
                txtPesquisa.setText(control.TextSize.maxLenghtCPFCNPJ(txtPesquisa.getText(), false));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "CEP":
                txtPesquisa.setText(control.TextSize.maxLenghtCep(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Logradouro":
                txtPesquisa.setText(control.TextSize.maxLenghtLogradouro(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Nr Logradouro":
                txtPesquisa.setText(control.TextSize.maxLenghtNrLogradouro(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Razão Social":
                txtPesquisa.setText(control.TextSize.maxLenghtNomeRazao(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Telefone":
                txtPesquisa.setText(control.TextSize.maxLenghtTelefone(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Ramal":
                txtPesquisa.setText(control.TextSize.maxLenghtCelularRamal(txtPesquisa.getText(), false));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Mantém Contrato?":
                lblDigiteODado.setText("Digite Sim ou Não:");
                txtPesquisa.setText(control.TextSize.maxLenghtContrato(txtPesquisa.getText()));
                modoPesquisaNormal();
                txtPesquisa.requestFocus();
                break;
            case "Data de Cadastro":
                modoPesquisaData(false);
                txtfDataDe.requestFocus();
                break;
            case "Data Entre/Até":
                lblDigiteODado.setText("Digite a Data Inicial:");
                modoPesquisaData(true);
                txtfDataDe.requestFocus();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro ao definir limite de caracteres do campo de pesquisa.",
                        "Erro - limite de dígitos dinâmico", 0);
                break;
        }
    }

    private void pesquisarFiltrada() {
        int opcaoFiltro = cmbFiltro.getSelectedIndex();
        int opcaoDataCadastro = 9;
        int opcaoDataDeAte = 10;

        if ((opcaoFiltro != opcaoDataCadastro) && (opcaoFiltro != opcaoDataDeAte)) {
            if (!"".equals(txtPesquisa.getText().trim())) {
                atualizarTabela(true);
            } else {
                limparTabela();
            }
        }
    }

    private void popularCampos() {
        PessoaJuridica pessoaJuridica = new PessoaJuridica();

        String cnpj = (String) tblListagemPessoaJ.getValueAt(tblListagemPessoaJ.getSelectedRow(), 1);

        pessoaJuridica = dao.DaoPessoa.popularPessoaJuridica(cnpj);
        boolean mantemContrato = pessoaJuridica.getPessoa().getManterContratoBooleano();

        if (mantemContrato) {
            rbtSimCadastro.setSelected(true);
            rbtNaoCadastro.setSelected(false);
        } else {
            rbtSimCadastro.setSelected(false);
            rbtNaoCadastro.setSelected(true);
        }
        txtfDataCadastro.setText(pessoaJuridica.getDataCadastro());
        txtNomePessoaFicticio.setText(pessoaJuridica.getPessoa().getNome());
        txtCpfCnpj.setText(pessoaJuridica.getCnpj());
        txtfCep.setText(pessoaJuridica.getPessoa().getEndereco().getCep());
        txtNumeroLogradouro.setText(pessoaJuridica.getPessoa().getComplementoLogradouro());
        txtTelefone.setText(String.valueOf(pessoaJuridica.getPessoa().getTelefone()));
        txtCelRamal.setText(String.valueOf(pessoaJuridica.getRamalCliente()));
        txtRazaoSocial.setText(pessoaJuridica.getRazaoSocial());
        PK_REF = pessoaJuridica.getCnpj();

        verificarCpfCnpjEmUso();
        verificarCep();
    }

    
    
    
}
