/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Texto;
import dao.DaoUsuario;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Luiz
 */
public class FrmLogin extends javax.swing.JFrame {
    
    //instanciando frm principal e login
//    FrmPrincipal principal = new FrmPrincipal();
//    FrmLogin telaLogin = new FrmLogin();
    
    public FrmLogin() throws IOException {
        control.ManipularArquivos.lerArquivoConfiguracoes();
        try {
            UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }
    
    public void logar() throws IOException{
        //Parametrizando dados do banco de dados ORACLE
        dao.Conexao.setServerName(txtf_IpBanco.getText());
        dao.Conexao.setServerPort(txt_portaBanco.getText());
        dao.Conexao.setUsername(txtp_usuarioDB.getText());
        dao.Conexao.setPassword(txtp_senhaDB.getText());
        dao.Conexao.setSid(txt_sid.getText());
        
        
        //chamando método de login de usuário
        int aux;
        aux = DaoUsuario.ChecarLogin(txtLogin.getText().trim(), txtPassword.getText().trim());
        
        if (aux == 0)
        {
            //Instanciando tela principal e chamando-a
            control.Janelas.abrirPrincipal();
            //Salva os parâmetros de login
            control.Opcoes.setLogin(txtLogin.getText());
            control.Opcoes.setIp(txtf_IpBanco.getText());
            control.Opcoes.setPorta(txt_portaBanco.getText());
            control.Opcoes.setSID(txt_sid.getText());
            control.Opcoes.setUsuarioDB(txtp_usuarioDB.getText());
            control.Opcoes.setSenhaDB(txtp_senhaDB.getText());
            
            control.ManipularArquivos.escreverArquivoConfiguracoes();
            
            //eliminando a tela de login da memória
            this.dispose();
        }
        else if (aux == 1)
        {
            JOptionPane.showMessageDialog(null, "Login e/ou Senha incorretos.\nTente novamente.", "Erro - não foi possível logar",0);
        } else {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLogin = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        BtnAcesso = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        panDadosDB = new javax.swing.JPanel();
        lbl_ip = new javax.swing.JLabel();
        lbl_porta = new javax.swing.JLabel();
        txt_portaBanco = new javax.swing.JTextField();
        lbl_user = new javax.swing.JLabel();
        txtp_usuarioDB = new javax.swing.JPasswordField();
        lbl_senhaDB = new javax.swing.JLabel();
        txtp_senhaDB = new javax.swing.JPasswordField();
        lbl_sid = new javax.swing.JLabel();
        txt_sid = new javax.swing.JTextField();
        txtf_IpBanco = new javax.swing.JFormattedTextField();
        btnPadrão = new javax.swing.JButton();
        btn_debugrun = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synchrosoft - Login");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logopng32.png")));
        setMaximumSize(new java.awt.Dimension(737, 372));
        setMinimumSize(new java.awt.Dimension(737, 372));
        setPreferredSize(new java.awt.Dimension(737, 372));
        setResizable(false);
        setSize(new java.awt.Dimension(737, 372));
        getContentPane().setLayout(null);

        jpnLogin.setAutoscrolls(true);
        jpnLogin.setOpaque(false);
        jpnLogin.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_nome_pequeno.png"))); // NOI18N
        jpnLogin.add(lblLogo);
        lblLogo.setBounds(0, 0, 360, 330);

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Login:");
        jpnLogin.add(jLabel2);
        jLabel2.setBounds(430, 30, 49, 25);

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        jpnLogin.add(jLabel3);
        jLabel3.setBounds(430, 90, 53, 25);

        txtLogin.setText(control.Opcoes.getLogin());
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginKeyReleased(evt);
            }
        });
        jpnLogin.add(txtLogin);
        txtLogin.setBounds(430, 60, 246, 25);

        BtnAcesso.setText("Acessar");
        BtnAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAcessoActionPerformed(evt);
            }
        });
        BtnAcesso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAcessoKeyPressed(evt);
            }
        });
        jpnLogin.add(BtnAcesso);
        BtnAcesso.setBounds(560, 160, 110, 30);

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jpnLogin.add(txtPassword);
        txtPassword.setBounds(430, 120, 246, 25);

        panDadosDB.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco de Dados"));
        panDadosDB.setOpaque(false);
        panDadosDB.setLayout(null);

        lbl_ip.setText("IP:");
        panDadosDB.add(lbl_ip);
        lbl_ip.setBounds(10, 19, 50, 14);

        lbl_porta.setText("Porta:");
        panDadosDB.add(lbl_porta);
        lbl_porta.setBounds(170, 19, 40, 14);

        txt_portaBanco.setText(control.Opcoes.getPorta());
        panDadosDB.add(txt_portaBanco);
        txt_portaBanco.setBounds(210, 16, 90, 20);

        lbl_user.setText("Usuário:");
        panDadosDB.add(lbl_user);
        lbl_user.setBounds(10, 45, 50, 14);

        txtp_usuarioDB.setText(control.Opcoes.getUsuarioDB());
        panDadosDB.add(txtp_usuarioDB);
        txtp_usuarioDB.setBounds(60, 42, 100, 20);

        lbl_senhaDB.setText("Senha:");
        panDadosDB.add(lbl_senhaDB);
        lbl_senhaDB.setBounds(10, 71, 50, 14);

        txtp_senhaDB.setText(control.Opcoes.getSenhaDB());
        panDadosDB.add(txtp_senhaDB);
        txtp_senhaDB.setBounds(60, 68, 100, 20);

        lbl_sid.setText("SID:");
        panDadosDB.add(lbl_sid);
        lbl_sid.setBounds(170, 45, 40, 14);

        txt_sid.setText(control.Opcoes.getSID());
        panDadosDB.add(txt_sid);
        txt_sid.setBounds(210, 42, 90, 20);

        try {
            txtf_IpBanco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtf_IpBanco.setText(control.Opcoes.getIp());
        panDadosDB.add(txtf_IpBanco);
        txtf_IpBanco.setBounds(60, 16, 100, 20);

        btnPadrão.setText("Padrão");
        btnPadrão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadrãoActionPerformed(evt);
            }
        });
        panDadosDB.add(btnPadrão);
        btnPadrão.setBounds(210, 68, 90, 20);

        jpnLogin.add(panDadosDB);
        panDadosDB.setBounds(420, 200, 310, 100);

        btn_debugrun.setText("Debug run");
        btn_debugrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_debugrunActionPerformed(evt);
            }
        });
        jpnLogin.add(btn_debugrun);
        btn_debugrun.setBounds(430, 160, 100, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        jpnLogin.add(lblBackground);
        lblBackground.setBounds(-30, -200, 1150, 650);

        getContentPane().add(jpnLogin);
        jpnLogin.setBounds(0, 0, 737, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAcessoActionPerformed
        try {
            logar();
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAcessoActionPerformed

    private void txtLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyReleased
        txtLogin.setText(Texto.maxLenghtLogin(txtLogin.getText()));
    }//GEN-LAST:event_txtLoginKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        txtPassword.setText(Texto.maxLenghtSenha(txtPassword.getText()));
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                logar();
            } catch (IOException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                logar();
            } catch (IOException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void BtnAcessoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAcessoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                logar();
            } catch (IOException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnAcessoKeyPressed

    private void btn_debugrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_debugrunActionPerformed
        control.Janelas.abrirPrincipal();
        control.SynchroSoft.setNvlAdm(1);
        dao.Conexao.setServerName(txtf_IpBanco.getText());
        dao.Conexao.setServerPort(txt_portaBanco.getText());
        dao.Conexao.setUsername(txtp_usuarioDB.getText());
        dao.Conexao.setPassword(txtp_senhaDB.getText());
        dao.Conexao.setSid(txt_sid.getText());
        this.dispose();
    }//GEN-LAST:event_btn_debugrunActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnPadrãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadrãoActionPerformed
        txtf_IpBanco.setText("192168100202");
        txt_portaBanco.setText("1521");
        txtp_usuarioDB.setText("system");
        txtp_senhaDB.setText("system");
        txtp_senhaDB.setText("system");
        txt_sid.setText("XE");
    }//GEN-LAST:event_btnPadrãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmLogin().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAcesso;
    private javax.swing.JButton btnPadrão;
    private javax.swing.JButton btn_debugrun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lbl_ip;
    private javax.swing.JLabel lbl_porta;
    private javax.swing.JLabel lbl_senhaDB;
    private javax.swing.JLabel lbl_sid;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel panDadosDB;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txt_portaBanco;
    private javax.swing.JTextField txt_sid;
    private javax.swing.JFormattedTextField txtf_IpBanco;
    private javax.swing.JPasswordField txtp_senhaDB;
    private javax.swing.JPasswordField txtp_usuarioDB;
    // End of variables declaration//GEN-END:variables
}
